### Gombosuren.A, MUST

Neural network for beginners

Нейрол нетвөрк энгийн жишээ

Энэхүү тэмдэглэлдээ нейрол нетвөрк загвар байгуулах, түүнийг хэрхэн хэрэгжүүлж болох талаар энгийн жишээ харууллаа.


In [22]:
# BUILD NEURAL NETWORK;
from random import choice;
import numpy as np;
np.random.seed(1);

# CREATE ACTIVATION FUNCTION; 
def activation(x):
    if x < 0.5:
        return 0;
    else:
        return 1;
 

training_data = [(np.array([0,0,1]), 0),
                 (np.array([0,1,1]), 0),
                 (np.array([1,0,1]), 0),
                 (np.array([1,1,1]), 1),
                ];
print("training data:\n ", training_data);
print("\nactivation function: ", activation);

training data:
  [(array([0, 0, 1]), 0), (array([0, 1, 1]), 0), (array([1, 0, 1]), 0), (array([1, 1, 1]), 1)]

activation function:  <function activation at 0x7fc98f8e7510>


In [23]:
# MODEL PARAMETERS;  
learning_rate = 0.2;
training_steps = 100;

print("learning rate: ", learning_rate);
print("steps: ", training_steps);

# INITIALIZE WEIGHTS;
W = np.random.rand(len(training_data[0][0])); 
print("initialize weights: ", W);

learning rate:  0.2
steps:  100
initialize weights:  [4.17022005e-01 7.20324493e-01 1.14374817e-04]


In [24]:
# MAIN;
for i in range(training_steps):
    x, y = choice(training_data);
    #print(x, y);
    L1 = np.dot(W, x);
    #print(L1);
    y_pred = activation(L1);
    #print(y_pred);
    error = y - y_pred;
    update = learning_rate * error * x; 
    W +=update;


In [25]:
# OUTPUT AFTER TRAINING; 
print("Predictions after training")
for x, _ in training_data:
    #print(x);
    y_pred = np.dot(x, W);
    #print(y_pred);
    print("{}: {}".format(x[:3], activation(y_pred)));

Predictions after training
[0 0 1]: 0
[0 1 1]: 0
[1 0 1]: 0
[1 1 1]: 1
